- hosts: all
  become: true

  tasks:

    - hostname:
        name: jump_host
    - name: add myself to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1[ \t]+localhost'
        line: '127.0.0.1 localhost jump_host'
        state: present
